apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-1wgg
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-qbqu-tenant/rhtap-demo-app/hacbs-test-project-1wgg@sha256:b5bb4a34abaea362bc57a49ca1079f24dd926775d200f5e87ce56326dbe11875
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
